version: "3.0"
services:
  node:
    image: "node:latest"
    working_dir: /
    tty: true
    volumes:
      - ./:/application
    command:
      - "bash"
  java:
    image: "openjdk:latest"
    tty: true
    volumes:
      - ./:/application
    